# Generated by Django 3.1.7 on 2021-07-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
