# Generated by Django 3.1.7 on 2021-04-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0002_remove_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DoctorID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorID', to='emrsystem.doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PatientID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientID', to='emrsystem.patient'),
        ),
    ]
