# Generated by Django 3.1.7 on 2021-07-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0002_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time_of_visit', models.TimeField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Unit', models.CharField(blank=True, choices=[('', ''), ('01', '01'), ('02', '02')], max_length=2)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emrsystem.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='emrsystem.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('patient', 'visit_number'), name='Visit Number'),
        ),
    ]
