# Generated by Django 3.1.7 on 2021-07-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0003_auto_20210718_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.DeleteModel(
            name='GynecHistory',
        ),
        migrations.DeleteModel(
            name='PastHistory',
        ),
    ]
