# Generated by Django 3.1.7 on 2021-04-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0003_auto_20210410_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('', ''), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_number', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_of_visit', models.TimeField(auto_now_add=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Unit', models.CharField(blank=True, choices=[('', ''), ('01', '01'), ('02', '02')], max_length=2)),
                ('PatientID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emrsystem.patient')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emrsystem.doctor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('PatientID', 'visit_number'), name='id'),
        ),
    ]
