# Generated by Django 3.1.7 on 2021-07-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0004_auto_20210718_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('SpO2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('general', models.TextField()),
                ('respiratory', models.TextField()),
                ('cardiovascular', models.TextField()),
                ('cereberovascular', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GynecHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gplad', models.CharField(blank=True, max_length=10, null=True)),
                ('edd', models.DateField(blank=True, null=True)),
                ('lmp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeries', models.TextField()),
                ('allergies', models.TextField()),
                ('general', models.TextField()),
                ('t2dm', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('hypothyroidism', models.BooleanField()),
                ('chronic_kidney_disease', models.BooleanField()),
                ('cardiovascular_disease', models.BooleanField()),
            ],
        ),
    ]
