# Generated by Django 3.1.7 on 2021-07-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0005_examination_gynechistory_pasthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='emrsystem.visit'),
        ),
        migrations.AddField(
            model_name='gynechistory',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gynec_histories', to='emrsystem.visit'),
        ),
        migrations.AddField(
            model_name='pasthistory',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_histories', to='emrsystem.visit'),
        ),
    ]
