# Generated by Django 3.1.7 on 2021-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0006_auto_20210718_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gynechistory',
            options={'verbose_name': 'Gynec History', 'verbose_name_plural': 'Gynec History'},
        ),
        migrations.AlterModelOptions(
            name='pasthistory',
            options={'verbose_name': 'Past History', 'verbose_name_plural': 'Past History'},
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
