# Generated by Django 3.1.7 on 2021-08-04 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0007_auto_20210718_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='time_of_visit',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='visit',
            name='time_till',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
