# Generated by Django 3.1.7 on 2021-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0008_auto_20210804_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(null=True),
        ),
    ]
