# Generated by Django 3.1.7 on 2021-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0009_patient_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
