# Generated by Django 3.1.7 on 2021-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0011_auto_20210905_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='oedema',
            field=models.BooleanField(default=False),
        ),
    ]
