# Generated by Django 3.1.7 on 2021-09-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0012_examination_oedema'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='per_abdominal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
