# Generated by Django 3.1.7 on 2021-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0013_examination_per_abdominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='local_examination',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
