# Generated by Django 3.1.7 on 2021-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0015_auto_20210911_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='cardiovascular',
            field=models.TextField(default='NAD'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cereberovascular',
            field=models.TextField(default='NAD'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='local_examination',
            field=models.TextField(default='NAD'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='others',
            field=models.TextField(default='NAD'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='per_abdominal',
            field=models.TextField(default='NAD'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='respiratory',
            field=models.TextField(default='NAD'),
        ),
    ]
