# Generated by Django 3.1.7 on 2021-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0016_auto_20210911_2010'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(fields=('visit',), name='Examination Number'),
        ),
    ]
