# Generated by Django 3.1.7 on 2021-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0017_auto_20210911_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='others',
            field=models.TextField(null=True),
        ),
    ]
