# Generated by Django 3.1.7 on 2021-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0018_auto_20210911_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_completed',
            field=models.BooleanField(default=False),
        ),
    ]
