# Generated by Django 3.1.7 on 2021-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0019_auto_20210912_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybaseuser',
            name='isDoctor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybaseuser',
            name='isPatient',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
