# Generated by Django 3.1.7 on 2021-09-18 14:08

from django.db import migrations, models
import emrsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0020_auto_20210918_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybaseuser',
            name='profilePic',
            field=models.ImageField(null=True, storage=emrsystem.models.OverwriteStorage(), upload_to=emrsystem.models.new_filename),
        ),
    ]
