# Generated by Django 3.1.7 on 2021-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0021_mybaseuser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybaseuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
    ]
