# Generated by Django 3.1.7 on 2021-09-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0022_mybaseuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
    ]
