# Generated by Django 3.1.7 on 2021-09-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0023_remove_patient_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybaseuser',
            old_name='gender',
            new_name='sex',
        ),
    ]
