# Generated by Django 3.1.7 on 2021-09-19 14:30

from django.db import migrations, models
import emrsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0024_auto_20210919_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, storage=emrsystem.models.OverwriteStorage(), upload_to=emrsystem.models.new_filename),
        ),
    ]
