# Generated by Django 3.1.7 on 2021-09-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0025_auto_20210919_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasthistory',
            name='visit',
        ),
        migrations.AddField(
            model_name='pasthistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_histories', to='emrsystem.patient'),
        ),
    ]
