# Generated by Django 3.1.7 on 2021-09-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0026_auto_20210920_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='isDoctor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mybaseuser',
            name='isPatient',
            field=models.BooleanField(null=True),
        ),
    ]
