# Generated by Django 3.1.7 on 2021-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0027_auto_20210928_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasthistory',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='cardiovascular_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='chronic_kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='general',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hypothyroidism',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='surgeries',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='t2dm',
            field=models.BooleanField(default=False),
        ),
    ]
