# Generated by Django 3.1.7 on 2021-10-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0028_auto_20211002_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasthistory',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='surgeries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
