# Generated by Django 3.1.7 on 2021-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0029_auto_20211002_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
