# Generated by Django 3.1.7 on 2021-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0031_auto_20211002_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='mybaseuser',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
