# Generated by Django 3.1.7 on 2021-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0032_auto_20211010_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasthistory',
            name='drugs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasthistory',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
    ]
