# Generated by Django 3.1.7 on 2021-10-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0034_auto_20211016_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
