# Generated by Django 3.1.7 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0035_auto_20211019_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
