# Generated by Django 3.1.7 on 2026-07-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0036_widen_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
