# Generated by Django 3.1.7 on 2026-07-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrsystem', '0037_nullable_complaints_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='SpO2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
